#!/usr/bin/env python3

# given two lists, output entries in both lists

import sys

with open(sys.argv[1]) as fd_provides:
    provides = [ x.strip() for x in fd_provides.readlines() ]

with open(sys.argv[2]) as fd_packages:
    packages = [ x.strip() for x in fd_packages.readlines() ]

for package in packages:
    if provides.count(package) > 0:
        print(package)
